name: Deploy Production

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/api/Dockerfile
          target: production
          push: true
          tags: ghcr.io/diogonsc/dlz-backend/dlz-api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no servidor
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd /opt/dlz-backend
            docker compose -f docker-compose.prod.yml --env-file .env.production pull api
            docker compose -f docker-compose.prod.yml --env-file .env.production up -d --no-deps api
            sleep 15
            /opt/dlz-backend/update-nginx.sh
            docker exec dlz_api /app/node_modules/.pnpm/prisma@6.19.3_typescript@5.9.3/node_modules/prisma/build/index.js migrate deploy --schema /app/packages/prisma/schema.prisma
            curl -f https://api.dlz.app.br/health
